In [1]:
import pandas as pd

In [2]:
Test = pd.read_csv('../../modesto/Data/ElectricityPrices/DAM_prices_and_volumes_hourly.csv', sep=';', 
                   parse_dates=True, dayfirst=True, index_col=0)

In [3]:
Test

,price_DE,volume_DE,price_FR,volume_FR,price_CH,volume_CH,price_BE,volume_BE
datetime_be,,,,,,,,
2005-02-08 00:00:00,0.03188,8218.2,NaN,NaN,NaN,NaN,0.03188,8218.2
2005-02-08 01:00:00,0.02937,8160.7,NaN,NaN,NaN,NaN,0.02937,8160.7
2005-02-08 02:00:00,0.03142,7702.9,NaN,NaN,NaN,NaN,0.03142,7702.9
2005-02-08 03:00:00,0.02978,8164.0,NaN,NaN,NaN,NaN,0.02978,8164.0
2005-02-08 04:00:00,0.03012,7635.6,NaN,NaN,NaN,NaN,0.03012,7635.6
2005-02-08 05:00:00,0.03209,7464.6,NaN,NaN,NaN,NaN,0.03209,7464.6
2005-02-08 06:00:00,0.03357,8666.6,NaN,NaN,NaN,NaN,0.03357,8666.6
2005-02-08 07:00:00,0.04407,9775.5,NaN,NaN,NaN,NaN,0.04407,9775.5
2005-02-08 08:00:00,0.04892,9979.7,NaN,NaN,NaN,NaN,0.04892,9979.7
2005-02-08 09:00:00,0.05039,10040.7,NaN,NaN,NaN,NaN,0.05039,10040.7
2005-02-08 10:00:00,0.05109,9749.1,NaN,NaN,NaN,NaN,0.05109,9749.1
2005-02-08 11:00:00,0.05299,10021.4,NaN,NaN,NaN,NaN,0.05299,10021.4
2005-02-08 12:00:00,0.04982,9976.7,NaN,NaN,NaN,NaN,0.04982,9976.7
2005-02-08 13:00:00,0.04977,9793.3,NaN,NaN,NaN,NaN,0.04977,9793.3
2005-02-08 14:00:00,0.04533,10093.4,NaN,NaN,NaN,NaN,0.04533,10093.4
2005-02-08 15:00:00,0.04054,10037.9,NaN,NaN,NaN,NaN,0.04054,10037.9
2005-02-08 16:00:00,0.04061,10607.0,NaN,NaN,NaN,NaN,0.04061,10607.0
2005-02-08 17:00:00,0.04299,10798.4,NaN,NaN,NaN,NaN,0.04299,10798.4
2005-02-08 18:00:00,0.07491,10916.4,NaN,NaN,NaN,NaN,0.07491,10916.4
2005-02-08 19:00:00,0.05277,10639.0,NaN,NaN,NaN,NaN,0.05277,10639.0
2005-02-08 20:00:00,0.04203,9241.9,NaN,NaN,NaN,NaN,0.04203,9241.9
2005-02-08 21:00:00,0.03605,8890.3,NaN,NaN,NaN,NaN,0.03605,8890.3
2005-02-08 22:00:00,0.03608,8706.2,NaN,NaN,NaN,NaN,0.03608,8706.2
2005-02-08 23:00:00,0.03001,8762.4,NaN,NaN,NaN,NaN,0.03001,8762.4
2005-02-09 00:00:00,0.03482,8456.9,NaN,NaN,NaN,NaN,0.03482,8456.9
2005-02-09 01:00:00,0.03221,8228.0,NaN,NaN,NaN,NaN,0.03221,8228.0
2005-02-09 02:00:00,0.03209,8093.3,NaN,NaN,NaN,NaN,0.03209,8093.3
2005-02-09 03:00:00,0.03005,8622.8,NaN,NaN,NaN,NaN,0.03005,8622.8
2005-02-09 04:00:00,0.02858,8122.4,NaN,NaN,NaN,NaN,0.02858,8122.4
2005-02-09 05:00:00,0.03305,8294.4,NaN,NaN,NaN,NaN,0.03305,8294.4
...,...,...,...,...,...,...,...,...
2017-09-01 16:00:00,0.03856,27025.5,0.03856,16163.2,0.04140,2165.6,0.03856,16163.2
2017-09-01 16:00:00,0.03856,27025.5,0.03856,16163.2,0.04140,2165.6,0.04140,2165.6
2017-09-01 17:00:00,0.04036,26555.6,0.04036,15222.3,0.04306,2166.6,0.04036,1831.0
2017-09-01 17:00:00,0.04036,26555.6,0.04036,15222.3,0.04306,2166.6,0.04036,26555.6
2017-09-01 17:00:00,0.04036,26555.6,0.04036,15222.3,0.04306,2166.6,0.04036,15222.3
2017-09-01 17:00:00,0.04036,26555.6,0.04036,15222.3,0.04306,2166.6,0.04306,2166.6
2017-09-01 18:00:00,0.04220,26064.0,0.04220,14454.4,0.04435,2920.9,0.04220,1787.3
2017-09-01 18:00:00,0.04220,26064.0,0.04220,14454.4,0.04435,2920.9,0.04220,26064.0
2017-09-01 18:00:00,0.04220,26064.0,0.04220,14454.4,0.04435,2920.9,0.04220,14454.4
2017-09-01 18:00:00,0.04220,26064.0,0.04220,14454.4,0.04435,2920.9,0.04435,2920.9
2017-09-01 19:00:00,0.04374,23823.7,0.04374,13816.6,0.04479,3186.9,0.04374,1885.3
2017-09-01 19:00:00,0.04374,23823.7,0.04374,13816.6,0.04479,3186.9,0.04374,23823.7
2017-09-01 19:00:00,0.04374,23823.7,0.04374,13816.6,0.04479,3186.9,0.04374,13816.6
2017-09-01 19:00:00,0.04374,23823.7,0.04374,13816.6,0.04479,3186.9,0.04479,3186.9
2017-09-01 20:00:00,0.04395,20485.3,0.04395,13067.8,0.04420,2975.6,0.04395,1584.2
2017-09-01 20:00:00,0.04395,20485.3,0.04395,13067.8,0.04420,2975.6,0.04395,20485.3
2017-09-01 20:00:00,0.04395,20485.3,0.04395,13067.8,0.04420,2975.6,0.04395,13067.8
2017-09-01 20:00:00,0.04395,20485.3,0.04395,13067.8,0.04420,2975.6,0.04420,2975.6
2017-09-01 21:00:00,0.03940,20825.8,0.03940,13107.6,0.04157,2531.2,0.03940,1467.5
2017-09-01 21:00:00,0.03940,20825.8,0.03940,13107.6,0.04157,2531.2,0.03940,20825.8
2017-09-01 21:00:00,0.03940,20825.8,0.03940,13107.6,0.04157,2531.2,0.03940,13107.6
2017-09-01 21:00:00,0.03940,20825.8,0.03940,13107.6,0.04157,2531.2,0.04157,2531.2
2017-09-01 22:00:00,0.03621,21281.0,0.03813,14586.4,0.03871,2342.1,0.03770,1219.4
2017-09-01 22:00:00,0.03621,21281.0,0.03813,14586.4,0.03871,2342.1,0.03621,21281.0
2017-09-01 22:00:00,0.03621,21281.0,0.03813,14586.4,0.03871,2342.1,0.03813,14586.4
2017-09-01 22:00:00,0.03621,21281.0,0.03813,14586.4,0.03871,2342.1,0.03871,2342.1
2017-09-01 23:00:00,0.03451,21293.9,0.03451,14496.8,0.03618,2003.2,0.03451,1420.3
2017-09-01 23:00:00,0.03451,21293.9,0.03451,14496.8,0.03618,2003.2,0.03451,21293.9
2017-09-01 23:00:00,0.03451,21293.9,0.03451,14496.8,0.03618,2003.2,0.03451,14496.8
2017-09-01 23:00:00,0.03451,21293.9,0.03451,14496.8,0.03618,2003.2,0.03618,2003.2

In [4]:
Test.to_csv('../../modesto/Data/ElectricityPrices/DAM_prices_and_volumes_hourly_new.csv', sep=';')